force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Is_SF__c.field-meta.xml
<CustomField>
    <fullName>Is_SF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is SF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Education__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Education</relationshipLabel>
    <relationshipName>Education</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Education__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <label>Institution</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education__c/fields/Passing_Date__c.field-meta.xml
<CustomField>
    <fullName>Passing_Date__c</fullName>
    <label>Passing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Demo_URL__c.field-meta.xml
<CustomField>
    <fullName>Demo_URL__c</fullName>
    <label>Demo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Description__c.field-meta.xml
<CustomField>
    <fullName>Project_Description__c</fullName>
    <label>Project Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/YT_Url__c.field-meta.xml
<CustomField>
    <fullName>YT_Url__c</fullName>
    <label>YT Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skills Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Skills</relationshipLabel>
    <relationshipName>Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Skill__c/fields/Proficiency__c.field-meta.xml
<CustomField>
    <fullName>Proficiency__c</fullName>
    <label>Proficiency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tools</fullName>
            </value>
            <value>
                <fullName>Technical Skills</fullName>
            </value>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill__c/fields/Skill_Value__c.field-meta.xml
<CustomField>
    <fullName>Skill_Value__c</fullName>
    <formula>IF(ISPICKVAL( Proficiency__c ,&apos;Low&apos;),0,IF(ISPICKVAL( Proficiency__c ,&apos;Medium&apos;),1,3))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Skill_Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Social_Media__c/Social_Media__c.object-meta.xml
<CustomObject>
    <label>Social Media</label>
    <nameField>
        <displayFormat>SM-{000}</displayFormat>
        <label>Social Media Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Media__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Social Media</relationshipLabel>
    <relationshipName>Social_Media</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Social_Media__c/fields/Icon_URL__c.field-meta.xml
<CustomField>
    <fullName>Icon_URL__c</fullName>
    <label>Icon URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Social_Media__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>YouTube</fullName>
            </value>
            <value>
                <fullName>GitHub</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Trailhead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Experience__c/Work_Experience__c.object-meta.xml
<CustomObject>
    <label>Work Experience</label>
    <nameField>
        <displayFormat>WE-{0000}</displayFormat>
        <label>Work Experience Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Experiences</relationshipLabel>
    <relationshipName>Work_Experiences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PortfolioController.cls
public without sharing class PortfolioController {
    @AuraEnabled(cacheable=true)
    public static List<scWrapper> getSocialMedia(){
        try {
            List<Social_Media__c> scList = [SELECt Id,Active__c,Icon_URL__c,Type__c,URL__c FROM Social_Media__c WHERE Contact__c=: System.Label.contactId AND Active__c=true];
        
            Set<string> sRNameSet=new Set<String>();
            for(Social_Media__c sc: scList){
                sRNameSet.add(sc.Icon_URL__c);
            }
            // List<StaticResource> srList= [SELECT Id,Name FROM StaticResource WHERE Name IN: sRNameSet];
            // Map<String,Id> srNameToIdMap= new Map<String,Id>();
            // for(StaticResource sr: srList){
            //     srNameToIdMap.put(sr.Name,sr.Id);
            // }

            List<scWrapper> retList= new List<scWrapper>();
            for(Social_Media__c sc: scList){
                scWrapper scw= new scWrapper();
                scw.url=sc.URL__c;
                scw.ssid=sc.Id;
                scw.iconUrl=sc.Icon_URL__c;
                retList.add(scw);
            }

            return retList;
        
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static Contact getContactDetails(){
        try {
            return [SELECT Id,Description,Summary__c,Work_Summary__c FROM Contact WHERE Id=: System.Label.contactId LIMIT 1];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Work_Experience__c> getWorkExperiences(){
        try {
           return [SELECT Id,Title__c,Company__c,To_Date__c,From_Date__c,Description__c FROM Work_Experience__c WHERE Contact__c =: System.Label.contactId]; 
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Skill__c> getSkills(){
        try {
            List<Skill__c> arList=[SELECT Id,Name,Contact__c,Proficiency__c,Section__c,Skill_Value__c FROM Skill__c WHERE Contact__c =: System.Label.contactId
            ORDER BY Section__c ASC,Skill_Value__c DESC];

            return arList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Education__c> getEducation(){
        try {
            List<Education__c> eduList=[SELECT Id,Name,Contact__c,Institution__c,Passing_Date__c FROm Education__c where Contact__c=: System.Label.contactId
             ORDER BY Passing_Date__c DESC];

             return eduList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled(cacheable=true)
    public static List<Certification__c> getCertifications(){
        try {
           List<Certification__c> certList=[SELECT Id,Is_SF__c,Name FROM Certification__c WHERE Contact__c =: System.Label.contactId ORDER BY CreatedDate DESC]; 
        return certList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled(cacheable=true)
    public static List<Project__c> getProjects(){
        try {
            List<Project__c> projList=[SELECT Id,Name FROM Project__c WHERE Contact__c =: System.Label.contactId ORDER BY CreatedDate DESC]; 
         return projList;
         } catch (Exception e) {
             throw new AuraHandledException(e.getMessage());
         }
    }


    @AuraEnabled(cacheable=true)
    public static Project__c getProjectDetails(String projectId){
        try {
            List<Project__c> projList=[SELECT Id,Name,Demo_URL__c,Project_Description__c,YT_Url__c FROM Project__c WHERE Id=:projectId];
            if(!projList.isEmpty()){
                return projList[0];
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return null;
    }

    public class scWrapper{
        @AuraEnabled 
        public String url{get;set;}
        @AuraEnabled 
        public String ssid{get;set;}
        @AuraEnabled
        public String iconUrl{get;set;}
    }
}