force-app/main/default/objects/WA_Message__c/WA_Message__c.object-meta.xml
<CustomObject>
    <label>WA Message</label>
    <nameField>
        <displayFormat>WA-{00000}</displayFormat>
        <label>WA Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WA Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WA_Message__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>WA Messages</relationshipLabel>
    <relationshipName>WA_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WA_Message__c/fields/Image_URL_new__c.field-meta.xml
<CustomField>
    <fullName>Image_URL_new__c</fullName>
    <label>Image URL</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WA_Message__c/fields/Message_Content__c.field-meta.xml
<CustomField>
    <fullName>Message_Content__c</fullName>
    <label>Message Content</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WA_Message__c/fields/WA_Id__c.field-meta.xml
<CustomField>
    <fullName>WA_Id__c</fullName>
    <label>WA Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WhatsappUtils.cls
public class WhatsappUtils {
    
    public String messaging_product;	//whatsapp
	public contacts[] contacts;
	public messages[] messages;
	class contacts {
		public String input;	//918455070614
		public String wa_id;	//918455070614
	}
	class messages {
		public String id;	//wamid.HBgMOTE4NDU1MDcwNjE0FQIAERgSMjRCQUQ5RjQxRTJDQzQxQUEyAA==
	}

    @AuraEnabled
    public static void sendTextMessage(String messageContent, String toPhone){
        HttpRequest req= new HttpRequest();
        req.setEndpoint('https://graph.facebook.com/v15.0/'+System.Label.Phone_Number_Id+'/messages');
        req.setMethod('POST');
        req.setHeader('content-type', 'application/json');
        req.setHeader('Authorization','Bearer '+System.Label.WhatsappAccessToken);
        system.debug('messageContent:'+messageContent);
        String reqBody='{"messaging_product": "whatsapp","recipient_type": "individual","to": "'+toPhone+'","type": "text","text": {"body": "'+messageContent+'"}}';
        req.setBody(reqBody);
        system.debug('reqBody->'+reqBody);
        Http http= new Http();
        
        try{
            HttpResponse response= http.send(req);
            system.debug('response:'+response.getBody());
            if(response.getStatusCode()==200){
                WA_Message__c createRec= new WA_Message__c();
				WhatsappUtils wutil=(WhatsappUtils)JSON.deserialize(response.getBody(), WhatsappUtils.class);
                createRec.WA_Id__c=wutil.contacts.size()>0?wutil.contacts.get(0).wa_id:null;
				createRec.Type__c='text';
				createRec.Message_Id__c= wutil.messages.size()>0?wutil.messages.get(0).id:null;
                createRec.Message_Content__c=messageContent;
                createRec.Profile_Name__c='Whatsapp Bot';
                if(createRec.WA_Id__c!=null){
                createRec.Contact__c=WhatsappMessage.getContact(createRec.WA_Id__c, createRec.Profile_Name__c);
                Insert createRec;
                }
            }
        }Catch(System.CalloutException ex){
            system.debug('ex.getMessage()'+ex.getMessage());
            system.debug('ex.getStackTraceString()'+ex.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static void sendImageMessage(String imgUrl, String toPhone){
        system.debug('IN WhatsappUtils.sendImageMessage()');
        HttpRequest req= new HttpRequest();
        req.setEndpoint('https://graph.facebook.com/v15.0/'+System.Label.Phone_Number_Id+'/messages');
        req.setMethod('POST');
        req.setHeader('content-type', 'application/json');
        req.setHeader('Authorization','Bearer '+System.Label.WhatsappAccessToken);
        String reqBody='{"messaging_product": "whatsapp","recipient_type": "individual","to": "'+toPhone+'","type": "image","image": {"link": "'+imgUrl+'"}}';
        req.setBody(reqBody);
        
        Http http= new Http();
        
        try{
            HttpResponse response= http.send(req);
            system.debug('response:'+response.getBody());
            if(response.getStatusCode()==200){
                WA_Message__c createRec= new WA_Message__c();
				WhatsappUtils wutil=(WhatsappUtils)JSON.deserialize(response.getBody(), WhatsappUtils.class);
                createRec.WA_Id__c=wutil.contacts.size()>0?wutil.contacts.get(0).wa_id:null;
				createRec.Type__c='image';
				createRec.Message_Id__c= wutil.messages.size()>0?wutil.messages.get(0).id:null;
                createRec.Image_URL_new__c=imgUrl;
                createRec.Profile_Name__c='Whatsapp Bot';
                if(createRec.WA_Id__c!=null){
                createRec.Contact__c=WhatsappMessage.getContact(createRec.WA_Id__c, createRec.Profile_Name__c);
                }
                Insert createRec;
            }
        }Catch(System.CalloutException ex){
            system.debug('ex.getMessage()'+ex.getMessage());
            system.debug('ex.getStackTraceString()'+ex.getStackTraceString());
        }
    }
}