force-app/main/default/objects/To_Do_Item__c/To_Do_Item__c.object-meta.xml
<CustomObject>
    <label>To Do Item</label>
    <nameField>
        <displayFormat>TDI-{000000}</displayFormat>
        <label>To Do Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>To Do Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do_Item__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>(&quot;Low&quot;)</defaultValue>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do_Item__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <label>Task</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/To_Do_Item__c/fields/To_Do_List__c.field-meta.xml
<CustomField>
    <fullName>To_Do_List__c</fullName>
    <label>To Do List</label>
    <referenceTo>To_Do_List__c</referenceTo>
    <relationshipLabel>To Do Items</relationshipLabel>
    <relationshipName>To_Do_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/To_Do_List__c/To_Do_List__c.object-meta.xml
<CustomObject>
    <label>To Do List</label>
    <nameField>
        <displayFormat>TDL-{000000}</displayFormat>
        <label>To Do List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>To Do Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do_List__c/fields/Home__c.field-meta.xml
<CustomField>
    <fullName>Home__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Home</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ScheduledToDoList.cls
global class ScheduledToDoList implements schedulable{
	
    global void execute(SchedulableContext ct){
        To_Do_List__c tdl=[SELECT Id,Home__c,List_Name__c FROM To_Do_List__c WHERE Home__c=true ORDER BY CreatedDate DESC LIMIT 1];
        To_Do_List__c td2= tdl.clone();
        td2.Id=NULL;
        td2.List_Name__c='TO DO LIST - '+DateTime.now().addDays(1).format('dd/MM/yyyy'); 	
        Insert td2;
        List<To_Do_Item__c> tdiList=[SELECT Id,To_Do_List__c,Task__c,Status__c,Priority__c FROM To_Do_Item__c
                                     WHERE To_Do_List__c=:tdl.Id AND Status__c!='Complete'];
        List<To_Do_Item__c> tdiList2=tdiList.clone();
        for(To_Do_Item__c tdi: tdiList2){
            tdi.To_Do_List__c=td2.Id;
            tdi.Id=NULL;
            if(tdi.Status__c=='In Progress'){
                tdi.Status__c='To Do';
            }
        }
        Insert tdiList2;
        
    }
    
}