force-app/main/default/objects/To_Do_Item__c/To_Do_Item__c.object-meta.xml
<CustomObject>
    <label>To Do Item</label>
    <nameField>
        <displayFormat>TDI-{000000}</displayFormat>
        <label>To Do Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>To Do Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do_Item__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>(&quot;Low&quot;)</defaultValue>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do_Item__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <label>Task</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/To_Do_Item__c/fields/To_Do_List__c.field-meta.xml
<CustomField>
    <fullName>To_Do_List__c</fullName>
    <label>To Do List</label>
    <referenceTo>To_Do_List__c</referenceTo>
    <relationshipLabel>To Do Items</relationshipLabel>
    <relationshipName>To_Do_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/To_Do_List__c/To_Do_List__c.object-meta.xml
<CustomObject>
    <label>To Do List</label>
    <nameField>
        <displayFormat>TDL-{000000}</displayFormat>
        <label>To Do List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>To Do Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do_List__c/fields/Home__c.field-meta.xml
<CustomField>
    <fullName>Home__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Home</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TD_Controller.cls
public without sharing class TD_Controller {
    
   
    @AuraEnabled(cacheable=true)
    public static TaskAndChild getChildTasks(String recordId){
        String listName='';
        if(recordId==System.Label.Default_Key){
            To_Do_List__c tdl=[SELECT Id,Home__c,List_Name__c FROM To_Do_List__c WHERE Home__c=true ORDER BY CreatedDate DESC LIMIT 1];
            recordId=tdl.Id;
            listName=tdl.List_Name__c;
        }else{
            To_Do_List__c tdl=[SELECT Id,Home__c,List_Name__c FROM To_Do_List__c WHERE Id=:recordId LIMIT 1];
            listName=tdl.List_Name__c;
        }
        List<To_Do_Item__c> childTaksList=[SELECT Id,Name,Status__c,Priority__c,To_Do_List__c,Task__c,To_Do_List__r.List_Name__c FROM To_Do_Item__c
         WHERE To_Do_List__c=: recordId ORDER BY Priority__c ASC, Task__c ASC];
        
         TaskAndChild retVal= new TaskAndChild();
         retVal.TaskName=listName;
         retVal.childTasks=childTaksList;

         return retVal;
    }


    @AuraEnabled
    public static Id createList(String listName){
        try {
            To_Do_List__c td= new To_Do_List__c();
            td.List_Name__c=listName;
            Insert td;

            return td.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void createRecord(String recString){
        try {
            Boolean isHome=false;
            if(recString.containsIgnoreCase(System.Label.Default_Key)){
                isHome=true;
                recString.replaceAll(System.Label.Default_Key,'');
            }
            To_Do_Item__c td=(To_Do_Item__c)JSON.deserialize(recString,To_Do_Item__c.class);
            
            if(isHome){
            To_Do_List__c tdl=[SELECT Id,Home__c FROM To_Do_List__c WHERE Home__c=true ORDER BY CreatedDate DESC LIMIT 1];
            td.To_Do_List__c=tdl.Id;
            }

            insert td;
        
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void updateRecord(String recString){
        try {
            To_Do_Item__c td=(To_Do_Item__c)JSON.deserialize(recString,To_Do_Item__c.class);
            update td;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void deleteRecord(String recId){
        try {
            To_Do_Item__c td=new To_Do_Item__c();
            td.Id=recId;
            delete td;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class TaskAndChild{
        @AuraEnabled public string TaskName;
        @AuraEnabled public List<To_Do_Item__c> childTasks;
    }
}